POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Elsa Pato",
    "number": 1155448877
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": 1155448877
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Elsa Pato"
}